### ISSUE TITLE
node_modules committed

### ISSUE THREAD

**Issue by senormeow** [JosephCarrington/Procedural-Platformer#11]
Looks like node_modules probably should of been in .gitignore

**Comment by senormeow** [comment]
Nevermind, I see you probably needed to commit it so you could server directly off github.io. Just sucks that the repo is bloated with over 10k files now.

**Comment by JosephCarrington** [comment]
No, it's a mistake. github pages just serves the docs directory and doesn't need node_modules at all. The node stuff is because I failed at making a shell script so did what I know: make a node server to watch files.

**Comment by JosephCarrington** [comment]
Node modules had been added to .gitignore, but cached files were not removed. They have been removed from the cache.
